// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5TjcHOP7OLlJAGRe3HhbRVG4-JkkhUmw',
    appId: '1:912600100803:web:cdc7a4726e145348275776',
    messagingSenderId: '912600100803',
    projectId: 'bookt-17d85',
    authDomain: 'bookt-17d85.firebaseapp.com',
    storageBucket: 'bookt-17d85.firebasestorage.app',
    measurementId: 'G-ZFJVYBEECZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNYmlMiDVAeBTEQO55UAO2cjTL774tGIU',
    appId: '1:912600100803:ios:94efd46fb5a9a855275776',
    messagingSenderId: '912600100803',
    projectId: 'bookt-17d85',
    storageBucket: 'bookt-17d85.firebasestorage.app',
    iosBundleId: 'com.example.bookt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5TjcHOP7OLlJAGRe3HhbRVG4-JkkhUmw',
    appId: '1:912600100803:web:556efef8c78f4d1f275776',
    messagingSenderId: '912600100803',
    projectId: 'bookt-17d85',
    authDomain: 'bookt-17d85.firebaseapp.com',
    storageBucket: 'bookt-17d85.firebasestorage.app',
    measurementId: 'G-7GN9SR0FB4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNYmlMiDVAeBTEQO55UAO2cjTL774tGIU',
    appId: '1:912600100803:ios:94efd46fb5a9a855275776',
    messagingSenderId: '912600100803',
    projectId: 'bookt-17d85',
    storageBucket: 'bookt-17d85.firebasestorage.app',
    iosBundleId: 'com.example.bookt',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC717V85eQ2LJzJpjpo8mJr3_DDAW3sJio',
    appId: '1:912600100803:android:5e30eef6761b6f0a275776',
    messagingSenderId: '912600100803',
    projectId: 'bookt-17d85',
    storageBucket: 'bookt-17d85.firebasestorage.app',
  );

}